const base = require("./base");

module.exports = {
  ...base,
  languageOptions: {
    ...base.languageOptions,
    parser: require("vue-eslint-parser"),
    parserOptions: {
      parser: require("@typescript-eslint/parser"),
      ecmaVersion: "latest",
      sourceType: "module",
      project: true,
    },
  },
  plugins: {
    ...base.plugins,
    vue: require("eslint-plugin-vue"),
    "@typescript-eslint": require("@typescript-eslint/eslint-plugin"),
  },
  rules: {
    ...base.rules,
    "no-unused-vars": "off",
    "@typescript-eslint/no-unused-vars": "off",
    "@typescript-eslint/no-floating-promises": "error",
    "@typescript-eslint/no-misused-promises": "error",
    "@typescript-eslint/consistent-type-imports": [
      "error",
      { prefer: "type-imports", fixStyle: "inline-type-imports" },
    ],

    "vue/component-name-in-template-casing": ["warn", "PascalCase"],
    "vue/component-definition-name-casing": ["warn", "PascalCase"],
    "vue/custom-event-name-casing": "warn",
    "vue/define-macros-order": "warn",
    "vue/html-closing-bracket-newline": "off",
    "vue/html-closing-bracket-spacing": "off",
    "vue/html-end-tags": "error",
    "vue/html-indent": "off",
    "vue/html-quotes": "off",
    "vue/html-self-closing": "off",
    "vue/max-attributes-per-line": "off",
    "vue/multiline-html-element-content-newline": "off",
    "vue/mustache-interpolation-spacing": "off",
    "vue/no-multi-spaces": "off",
    "vue/no-spaces-around-equal-signs-in-attribute": "off",
    "vue/no-template-shadow": "warn",
    "vue/one-component-per-file": "error",
    "vue/prop-name-casing": "off",
    "vue/require-default-prop": "off",
    "vue/require-explicit-emits": "warn",
    "vue/require-prop-types": "off",
    "vue/singleline-html-element-content-newline": "off",
    "vue/v-bind-style": "off",
    "vue/v-on-style": "off",
    "vue/v-slot-style": "off",
    "vue/attribute-hyphenation": "off",
    "vue/component-tags-order": [
      "warn",
      {
        order: ["script", "template", "style"],
      },
    ],
    "vue/define-emits-declaration": "warn",
    "vue/define-props-declaration": "warn",
    "vue/no-duplicate-attributes": "error",
    "vue/no-empty-component-block": "warn",
    "vue/no-multiple-object-in-class": "error",
    "vue/no-multiple-slot-args": "error",
    "vue/no-reserved-component-names": "error",
    "vue/no-static-inline-styles": "warn",
    "vue/no-template-key": "error",
    "vue/no-textarea-mustache": "error",
    "vue/no-unused-components": "warn",
    "vue/no-unused-refs": "warn",
    "vue/no-unused-v-else-if": "error",
    "vue/no-use-v-if-with-v-for": "error",
    "vue/no-useless-mustaches": "warn",
    "vue/no-useless-v-bind": "warn",
    "vue/prefer-separate-static-class": "warn",
    "vue/prefer-true-attribute-shorthand": "warn",
    "vue/require-toggle-inside-transition": "error",
    "vue/use-v-on-exact": "warn",
    "vue/valid-v-bind-sync": "error",
    "vue/valid-v-bind": "error",
    "vue/valid-v-cloak": "error",
    "vue/valid-v-else-if": "error",
    "vue/valid-v-else": "error",
    "vue/valid-v-for": "error",
    "vue/valid-v-html": "error",
    "vue/valid-v-if": "error",
    "vue/valid-v-is": "error",
    "vue/valid-v-memo": "error",
    "vue/valid-v-model": "error",
    "vue/valid-v-on": "error",
    "vue/valid-v-once": "error",
    "vue/valid-v-pre": "error",
    "vue/valid-v-show": "error",
    "vue/valid-v-slot": "error",
    "vue/valid-v-text": "error",
  },
};
